[versions]
agp = "9.4.1"
kotlin = "2.4.20"
coroutines = "1.11.0"
appcompat = "1.8.0"
wear = "1.4.0"
playServicesWearable = "20.0.1"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-wear = { module = "androidx.wear:wear", version.ref = "wear" }
play-services-wearable = { module = "com.google.android.gms:play-services-wearable", version.ref = "playServicesWearable" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
